import { serve } from "https://deno.land/std@0.190.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface AlertEmailRequest {
  user_id: string;
  alert_type: 'info' | 'warning' | 'critical';
  title: string;
  message: string;
  parent_email?: string;
}

const getAlertColor = (type: string) => {
  switch (type) {
    case 'critical': return '#ef4444';
    case 'warning': return '#f59e0b';
    default: return '#3b82f6';
  }
};

const getAlertIcon = (type: string) => {
  switch (type) {
    case 'critical': return '🚨';
    case 'warning': return '⚠️';
    default: return 'ℹ️';
  }
};

serve(async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { user_id, alert_type, title, message, parent_email }: AlertEmailRequest = await req.json();
    
    console.log("Received alert email request:", { user_id, alert_type, title });

    if (!parent_email) {
      console.log("No parent email provided, skipping email notification");
      return new Response(JSON.stringify({ success: true, skipped: true }), {
        status: 200,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    if (!RESEND_API_KEY) {
      console.error("RESEND_API_KEY not configured");
      return new Response(JSON.stringify({ error: "Email service not configured" }), {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      });
    }

    const color = getAlertColor(alert_type);
    const icon = getAlertIcon(alert_type);

    const emailResponse = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Study Monitor <onboarding@resend.dev>",
        to: [parent_email],
        subject: `${icon} ${title} - Study Monitor Alert`,
        html: `
          <!DOCTYPE html>
          <html>
          <head>
            <style>
              body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0a0a0f; color: #e5e5e5; padding: 40px 20px; }
              .container { max-width: 500px; margin: 0 auto; background: #1a1a2e; border-radius: 16px; padding: 32px; border: 1px solid #2a2a4a; }
              .header { text-align: center; margin-bottom: 24px; }
              .icon { font-size: 48px; margin-bottom: 16px; }
              .alert-badge { display: inline-block; padding: 6px 16px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: uppercase; background: ${color}20; color: ${color}; border: 1px solid ${color}40; }
              h1 { font-size: 24px; margin: 16px 0 8px; color: #ffffff; }
              .message { font-size: 16px; line-height: 1.6; color: #a0a0a0; margin: 24px 0; padding: 16px; background: #0f0f1a; border-radius: 12px; border-left: 4px solid ${color}; }
              .footer { text-align: center; font-size: 12px; color: #666; margin-top: 32px; padding-top: 24px; border-top: 1px solid #2a2a4a; }
              .btn { display: inline-block; padding: 12px 24px; background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; text-decoration: none; border-radius: 8px; font-weight: 600; margin-top: 16px; }
            </style>
          </head>
          <body>
            <div class="container">
              <div class="header">
                <div class="icon">${icon}</div>
                <span class="alert-badge">${alert_type.toUpperCase()} ALERT</span>
                <h1>${title}</h1>
              </div>
              <div class="message">
                ${message}
              </div>
              <div style="text-align: center;">
                <a href="#" class="btn">View Full Dashboard</a>
              </div>
              <div class="footer">
                <p>This alert was generated by Study Monitor</p>
                <p>You're receiving this because you have email alerts enabled.</p>
              </div>
            </div>
          </body>
          </html>
        `,
      }),
    });

    const emailData = await emailResponse.json();
    console.log("Email sent successfully:", emailData);

    return new Response(JSON.stringify({ success: true, data: emailData }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    console.error("Error sending alert email:", errorMessage);
    return new Response(
      JSON.stringify({ error: errorMessage }),
      { status: 500, headers: { "Content-Type": "application/json", ...corsHeaders } }
    );
  }
});
